global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    dns_sd_configs:
      - names:
        - 'tasks.node-exporter'
        type: 'A'
        port: 9100

  # cAdvisor bị bỏ qua vì không tương thích với ARM
  # - job_name: 'cadvisor'
  #   dns_sd_configs:
  #     - names:
  #       - 'tasks.cadvisor'
  #       type: 'A'
  #       port: 8080

  - job_name: 'dockercoins'
    dns_sd_configs:
      - names:
        - 'tasks.rng'
        - 'tasks.hasher'
        - 'tasks.webui'
        - 'tasks.worker'
        type: 'A'
        port: 80

remote_write:
  - url: "http://influxdb:8086/api/v1/prom/write?db=prometheus"

remote_read:
  - url: "http://influxdb:8086/api/v1/prom/read?db=prometheus"
