cluster.name: "docker-cluster"
network.host: 0.0.0.0
discovery.type: single-node
xpack.security.enabled: false
xpack.monitoring.collection.enabled: true

# Thêm các cấu hình để giảm bộ nhớ và tăng độ ổn định
cluster.routing.allocation.disk.threshold_enabled: false
bootstrap.memory_lock: true
http.cors.enabled: true
http.cors.allow-origin: "*"
node.master: true
node.data: true
node.ingest: true
