server.name: kibana
server.host: "0.0.0.0"
elasticsearch.hosts: ["http://elasticsearch:9200"]
monitoring.ui.container.elasticsearch.enabled: true

# Tắt xác thực và bỏ qua màn hình chào mừng
xpack.security.enabled: false
xpack.security.authc.providers: []
xpack.security.authc.api_key.enabled: false
xpack.reporting.roles.enabled: false
telemetry.enabled: false
telemetry.optIn: false
xpack.reporting.enabled: false
xpack.security.audit.enabled: false
xpack.encryptedSavedObjects.encryptionKey: "encryptionkeythatis32charactersl"
elasticsearch.username: ""
elasticsearch.password: ""
xpack.fleet.agents.enabled: false
xpack.fleet.agents.elasticsearch.hosts: ["http://elasticsearch:9200"]
xpack.fleet.agents.fleet_server.hosts: ["http://fleet-server:8220"]
xpack.fleet.packages: []
xpack.fleet.enabled: false
xpack.fleet.registryUrl: ""
xpack.security.encryptionKey: "encryptionkeythatis32charactersl"
